// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLyOiTIEiTJdZ95gN389kUdBO1MXa6wV0',
    appId: '1:340156629592:web:dc735629b7603d83bfc02d',
    messagingSenderId: '340156629592',
    projectId: 'examapp-7ded6',
    authDomain: 'examapp-7ded6.firebaseapp.com',
    storageBucket: 'examapp-7ded6.appspot.com',
    measurementId: 'G-22SEQ3FX6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA65gDoiK7tRgNJFydiTvDDCBwRsfrZ7Ao',
    appId: '1:340156629592:android:9a84c923859777cdbfc02d',
    messagingSenderId: '340156629592',
    projectId: 'examapp-7ded6',
    storageBucket: 'examapp-7ded6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-hknKKfskre0bZDPGOh9JdsviVzZ0yY',
    appId: '1:340156629592:ios:58c5d54ce445430fbfc02d',
    messagingSenderId: '340156629592',
    projectId: 'examapp-7ded6',
    storageBucket: 'examapp-7ded6.appspot.com',
    iosClientId: '340156629592-28r9riaq68ed151h7187pbfc1ap5if3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.examapp',
  );
}
